### ISSUE TITLE
Script halted exception In Azure Powershell functions

### ISSUE THREAD

**Issue by sindhushree15** [andres-canello/AzureADAuthMethods#1]
Hi,
Am trying to integrate this solution in Azure Power shell function with valid app registrations getting "Script Halted" Exception while loading the Module. But it works fine with manual run from cmdlet , was able to push mobile number to Authentication Methods. 
<img width="811" alt="Error" src="https://user-images.githubusercontent.com/15727109/98621175-b1981780-232c-11eb-88b2-404c246d9f0a.PNG">

Powershell version on Azure 
<img width="356" alt="Version" src="https://user-images.githubusercontent.com/15727109/98621321-0176de80-232d-11eb-9ee9-4d7c370c2f0a.PNG">

 Kindly help me to get this sorted out.

**Comment by andres-canello** [comment]
Hi @sindhushree15 , I don't see any info there to be able to comment on what the issue could be. Would you be able to make sure the required modules are importing correctly?
Another approach would be using the official Graph module, instructions here: https://docs.microsoft.com/en-gb/azure/active-directory/authentication/howto-mfa-userdevicesettings

**Comment by sindhushree15** [comment]
Hi Andres,

Thanks for the response. 
Actually am trying for auto enabling MFA using "Azure App services - power shell  function" in our application behalf of app users.
I tried this Module With Azure PowerShell alone, while importing module itself throwing Script halted exception and couldn't load it. 
I just checked the script and found that Get-MsalToken is happening in interactive way. Is there way to achieve this in non-interactive way for our users? 
I just extracted Set-AzureADUserAuthenticationMethod script alone from this solution and trying , now i need to pass credentials while generating token instead of popup window. Is that possible?
I did some research but didn't get enough info. My requirement is just to push mobile number in Authentication Methods as shown below
<img width="684" alt="Phone" src="https://user-images.githubusercontent.com/15727109/98668705-45420600-2376-11eb-975a-d8a7dc4dad8e.PNG">

Am new to azure so please guide me on this.

**Comment by andres-canello** [comment]
Ah that is probably the reason it's breaking. We will have App Permissions for the Authentication Methods API soon, so you'll be able to authenticate using a Service Principal and a certificate. Here is an example on how to generate the SP and cert: https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0#example-3--connect-a-session-as-a-service-principal so you can get ready.

**Comment by sindhushree15** [comment]
Hi Andres,

Thanks for the info. 
I have one more query, please clarify. 
We were using below script to enable MFA as per the documentation. 

import-module 'D:\Home\site\wwwroot\EIMMFARegistration\MyModules\MSOnline\1.1.183.17\MSOnline.psd1'


    # Connect/log-in to Azure AD using Connect-MsolService (Service Principals not supported)
    Connect-MsolService –Credential $UserCredential -ErrorAction Stop

    $st = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationRequirement
    $st.RelyingParty = "*"
    $st.State = "Enforced"
    $sta = @($st)

 
    $sm1 = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
    $sm1.IsDefault = $true
    $sm1.MethodType = "OneWaySMS"

    $sm2 = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
    $sm2.IsDefault = $false
    $sm2.MethodType = "TwoWayVoiceMobile"
    $sm = @($sm1, $sm2)
    
    # Perform MFA Registration / Strong Authentication
    Set-MsolUser -ObjectId $upn -StrongAuthenticationRequirements @() -StrongAuthenticationMethods $sm -ErrorAction Stop
 
It was working fine till August and stopped working afterwards. Users are getting following error while completing the registration. 

<img width="247" alt="Error Message" src="https://user-images.githubusercontent.com/15727109/98773384-d5cc2500-240e-11eb-8653-4826f225f125.PNG">


Unable to find out root cause , because of this we are replacing the script with Authentication Methods API. Any idea like why it is failing?

**Comment by andres-canello** [comment]
The method above was never supported and doesn't work anymore for cloud-only users. Please see this: https://techcommunity.microsoft.com/t5/azure-active-directory-identity/updates-to-managing-user-authentication-methods/ba-p/1751705

**Comment by sindhushree15** [comment]
Received your email, Thanks for the clarification Andres. I have integrated Graph API with C#.
